client-gif:
  name: gif
  token: p247iQfyW7b9WG1kymhXqbnxX43SRer4
  post:
    baseUrl: https://api.giphy.com/v1/gifs/random

client-exchange:
  name: exchange
  token: 0f4a4899ab5b42509ad26286b0e95fbf
  category-one: rich
  category-two: broken
  post:
    baseUrl: https://openexchangerates.org/api